(function(){
'use strict';
const V=window.NATFIBER_EDITOR_VERSION||'1.6.0',KEY='natfiber_admin_fiber',EV='natfiber:fiber-changed';
const S=window.NATFIBER_ADMIN_STATE=window.NATFIBER_ADMIN_STATE||{activeFiberId:localStorage.getItem(KEY)||'NF-0001',fibers:[],dashboard:null,role:null};
const $=s=>document.querySelector(s),valid=id=>/^NF-\d{4}$/.test(String(id||''));
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>{try{return window.NF_I18N?.getLang?.()||localStorage.getItem('natfiber_lang')||'id'}catch{return'id'}};
const L=(id,en)=>lang()==='id'?id:en;
let sb=null,seq=0;
function version(){const e=$('.side-brand span'),x=`Editor v${V} · Stable`;if(e&&e.textContent!==x)e.textContent=x;document.documentElement.dataset.natfiberEditorVersion=V}
function shell(){const top=$('.editor-top .top-actions');if(!top)return null;let s=$('#adminFiberSelector');if(s)return s;const w=document.createElement('div');w.className='nf-fiber-selector-wrap nf-stable-selector';w.innerHTML=`<label>${L('SERAT AKTIF','ACTIVE FIBER')}</label><select id="adminFiberSelector" aria-label="Active fiber"></select>`;top.insertBefore(w,top.firstChild);return $('#adminFiberSelector')}
function active(){return S.activeFiberId||localStorage.getItem(KEY)||'NF-0001'}
function setActive(id,{emit=true,source='stable-core'}={}){if(!valid(id))return false;const changed=S.activeFiberId!==id;S.activeFiberId=id;localStorage.setItem(KEY,id);const s=$('#adminFiberSelector');if(s&&[...s.options].some(o=>o.value===id)&&s.value!==id)s.value=id;if(changed&&emit)window.dispatchEvent(new CustomEvent(EV,{detail:{fiberId:id,source}}));return true}
function bind(){const s=shell();if(!s||s.dataset.nfStableBound)return;s.dataset.nfStableBound='1';s.addEventListener('change',()=>{setActive(s.value,{source:'selector'});version()},true)}
function fill(fibers){const s=shell(),rows=(fibers||[]).filter(f=>valid(f?.fiber_id)).sort((a,b)=>a.fiber_id.localeCompare(b.fiber_id));if(!s||!rows.length)return;S.fibers=rows;const keep=rows.some(f=>f.fiber_id===active())?active():rows[0].fiber_id;s.replaceChildren(...rows.map(f=>{const o=document.createElement('option');o.value=f.fiber_id;o.textContent=`${f.fiber_id} · ${f.canonical_name||f.english_name||''}`;return o}));s.value=keep;setActive(keep,{emit:false,source:'db-sync'});bind()}
function style(){if($('#nfStableCoreStyle'))return;const s=document.createElement('style');s.id='nfStableCoreStyle';s.textContent=`.nf-stable-selector{display:flex;align-items:center;gap:8px;padding:6px 8px 6px 12px;border:1px solid #d8e5df;border-radius:999px;background:#fff}.nf-stable-selector label{font-size:9px;font-weight:800;letter-spacing:.08em;color:#698078;white-space:nowrap}.nf-stable-selector #adminFiberSelector{border:0;background:#eef6f2;color:#173f33;font-weight:800;border-radius:999px;padding:8px 30px 8px 12px;outline:none;cursor:pointer;max-width:260px}.nf-stable-dashboard-scope{margin:0 0 14px;padding:12px 15px;border:1px solid #d8e5df;background:#f3f8f5;border-radius:14px;display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.nf-stable-dashboard-scope strong{color:#173f33}.nf-stable-dashboard-scope span{font-size:10px;color:#687a72}.nf-stable-dashboard-meta{display:flex;gap:8px;flex-wrap:wrap}.nf-stable-dashboard-meta i{font-style:normal;font-size:9px;font-weight:800;padding:4px 7px;border-radius:999px;background:#e2efe8;color:#245c48}@media(max-width:1000px){.nf-stable-selector label{display:none}.nf-stable-selector #adminFiberSelector{max-width:210px}}`;document.head.appendChild(s)}
function scope(p,d){if(!p?.fiber||!$('#summaryCards'))return;let e=$('#nfStableDashboardScope');if(!e){e=document.createElement('div');e.id='nfStableDashboardScope';e.className='nf-stable-dashboard-scope';$('#summaryCards').before(e)}e.innerHTML=`<div><strong>${esc(p.fiber.fiber_id)} · ${esc(p.fiber.canonical_name||'')}</strong><br><span>${esc(p.fiber.scientific_name||'')} · ${esc(L('konteks serat aktif','active fiber context'))}</span></div><div class="nf-stable-dashboard-meta"><i>${L('Database','Database')}: ${esc(d?.fibers_total??S.fibers.length)} ${L('serat','fibers')}</i><i>${L('Publik','Published')}: ${esc(d?.fibers_published??'—')}</i><i>${L('Peran','Role')}: ${esc(d?.role||S.role||'—')}</i></div>`}
function cards(p){if(!p||!$('#summaryCards'))return;const c=(p.conflicts||[]).filter(x=>!['RESOLVED','CLOSED'].includes(String(x.status||'').toUpperCase())).length,rows=[[L('Referensi serat','Fiber references'),(p.references||[]).length],[L('Observasi properti','Property observations'),(p.properties||[]).length],[L('Perlakuan','Treatments'),(p.treatments||[]).length],[L('Sistem komposit','Composite systems'),(p.composites||[]).length],[L('Rute proses','Processing routes'),(p.processing||[]).length],[L('Aplikasi','Applications'),(p.applications||[]).length],[L('Rekaman karakterisasi','Characterization records'),(p.characterization_records||[]).length],[L('Media publik','Public media'),(p.media||[]).length],[L('Konflik terbuka','Open conflicts'),c]];$('#summaryCards').innerHTML=rows.map(([k,v])=>`<div class="summary-card"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('')}
async function client(){if(sb)return sb;const c=window.NATFIBER_CONFIG||{};if(!c.supabaseUrl||!c.publishableKey)return null;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');return sb=m.createClient(c.supabaseUrl,c.publishableKey)}
async function refresh(){const n=++seq;try{const x=await client();if(!x)return;const {data:{session}}=await x.auth.getSession();if(!session)return;const {data:d,error:e}=await x.rpc('get_natfiber_editor_dashboard');if(e||!d||n!==seq)return;S.dashboard=d;S.role=d.role||null;fill(d.fibers||[]);const {data:p,error:pe}=await x.rpc('get_natfiber_profile',{target_fiber_id:active()});if(pe||n!==seq)return;scope(p,d);cards(p);version()}catch(e){console.warn('[NatFiber] Stabilization Patch 1 refresh failed',e)}}
function boot(){style();shell();bind();version();setActive(active(),{emit:false,source:'boot'});const brand=$('.side-brand');if(brand)new MutationObserver(version).observe(brand,{childList:true,subtree:true,characterData:true});const app=$('#editorApp');if(app){const go=()=>{version();bind();if(!app.hidden)refresh()};new MutationObserver(go).observe(app,{attributes:true,attributeFilter:['hidden']});go()}window.addEventListener(EV,()=>{version();refresh()});document.addEventListener('click',e=>{if(e.target?.closest('#refreshBtn'))setTimeout(refresh,80);if(e.target?.closest('.language-switch [data-lang]'))setTimeout(()=>{version();refresh()},80)})}
window.NATFIBER_ADMIN=Object.freeze({version:V,state:S,getActiveFiber:active,setActiveFiber:setActive,refreshFibers:refresh,fiberEvent:EV});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
