// NatFiber Encyclopedia — client configuration v1.7.1 · Admin Stabilization Patch 1
window.NATFIBER_EDITOR_VERSION='1.6.0';
window.NATFIBER_CONFIG={supabaseUrl:'https://ennnhgrffgoeqjvhpelh.supabase.co',publishableKey:'sb_publishable_ftskQZKSALKljnfIfY635g_YR-vvO4H'};
function nfLoadScript(src,{module=false,onload=null,onerror=null}={}){const s=document.createElement('script');if(module)s.type='module';s.src=src;if(onload)s.onload=onload;if(onerror)s.onerror=onerror;document.head.appendChild(s);return s;}
if(/\/admin\.html$/.test(window.location.pathname)){
 nfLoadScript('admin-stabilization-v1.6.0.js?v=1.6.0',{onload:()=>{
   nfLoadScript('fiber-admin-switcher-v1.3.4.js?v=1.3.4',{module:true});
   nfLoadScript('ijuk-global-admin-v1.1.js?v=1.1.3',{module:true});
   nfLoadScript('ijuk-media-admin-v1.0.js?v=1.0.3',{module:true});
   nfLoadScript('ijuk-characterization-dr3-admin-v1.0.js?v=1.0.3',{module:true});
   nfLoadScript('sisal-gold-audit-admin-v1.0.js?v=1.0.3',{module:true});
   nfLoadScript('ijuk-applications-t4-release-admin-v1.1.js?v=1.1',{module:true});
   nfLoadScript('jute-full-record-admin-v1.0.js?v=1.0',{module:true});
   nfLoadScript('jute-media-release-admin-v1.0.js?v=1.0',{module:true});
   nfLoadScript('flax-full-record-admin-v1.0.js?v=1.0',{module:true});
   nfLoadScript('flax-post-audit-release-admin-v1.0.js?v=1.0',{module:true});
   nfLoadScript('hemp-full-record-admin-v1.0.js?v=1.0',{module:true});
   nfLoadScript('batch-full-record-admin-v1.0.js?v=1.0',{module:true});
   nfLoadScript('product-media-admin-v1.2.js?v=1.2',{module:true,onload:()=>nfLoadScript('product-media-quick-entry-v1.2.1.js?v=1.2.1')});
 }});
}else{
 window.addEventListener('load',()=>{
   nfLoadScript('global-footprint-fiber-aware-v1.4.js?v=1.4.3',{
     onload:()=>nfLoadScript('jute-public-qa-v1.0.js?v=1.0',{
       onload:()=>nfLoadScript('flax-public-qa-v1.0.js?v=1.0',{
         onload:()=>nfLoadScript('hemp-public-qa-v1.0.js?v=1.0',{
           onload:()=>nfLoadScript('public-qa-fiber-aware-v1.4.js?v=1.4.3',{
             onload:()=>nfLoadScript('quality-certification-v1.0.js?v=1.0.3',{
               onload:()=>nfLoadScript('product-application-gallery-v1.1.js?v=1.1.3',{module:true})
             })
           })
         })
       })
     })
   });
 },{once:true});
}