import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const CFG=window.NATFIBER_CONFIG||{};if(!CFG.supabaseUrl||!CFG.publishableKey)throw new Error('NatFiber config missing');
const sb=createClient(CFG.supabaseUrl,CFG.publishableKey),FIBER_ID='NF-0004',GROUP='FLAX_POST_AUDIT_V1',$=s=>document.querySelector(s),esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let role=null,busy=false,lastFiber=null;
function activeFiber(){return $('#adminFiberSelector')?.value||localStorage.getItem('natfiber_admin_fiber')||'NF-0001'}
async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw error;return data}
async function resolveRole(){try{const {data:{session}}=await sb.auth.getSession();if(!session){role=null;return null}const d=await rpc('get_natfiber_editor_dashboard');role=d?.role||null}catch{role=null}return role}
function addStyle(){if($('#nfFlaxPostStyle'))return;const s=document.createElement('style');s.id='nfFlaxPostStyle';s.textContent=`body.nf-flax-active #view-preview > #nfFlaxPostAuditPanel.panel{display:block!important}#nfFlaxPostAuditPanel{border:2px solid #7863a8;box-shadow:0 10px 30px rgba(90,70,135,.08);margin-bottom:20px}#nfFlaxPostAuditPanel[hidden]{display:none!important}.nf-fp-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.nf-fp-head h3{margin:4px 0 6px}.nf-fp-head p{margin:0;color:#66776f;font-size:11px;line-height:1.55;max-width:800px}.nf-fp-actions{display:flex;gap:8px;flex-wrap:wrap}.nf-fp-note{margin:14px 0;padding:12px 14px;border:1px solid #ddd7ea;border-radius:12px;background:#faf8ff;font-size:10.5px;line-height:1.6;color:#5d5372}.nf-fp-table{overflow:auto;border:1px solid #e3dff0;border-radius:12px}.nf-fp-table table{width:100%;border-collapse:collapse;min-width:780px}.nf-fp-table th,.nf-fp-table td{padding:8px 10px;border-bottom:1px solid #eeeaf5;text-align:left;vertical-align:top;font-size:9.5px}.nf-fp-table th{background:#f7f5fb}.nf-fp-ok{color:#246947;font-weight:800}`;document.head.appendChild(s)}
function ensurePanel(){const host=$('#view-preview');if(!host)return null;let p=$('#nfFlaxPostAuditPanel');if(p)return p;p=document.createElement('article');p.id='nfFlaxPostAuditPanel';p.className='panel';p.innerHTML=`<div class="nf-fp-head"><div><span class="eyebrow">NF-0004 · POST-PUBLICATION AUDIT REPAIR</span><h3>Flax — Raman Characterization Supplement</h3><p>Audit menemukan Raman sudah source-resolved tetapi tertahan oleh enum characterization lama. Supplement ini hanya mempublikasikan 1 record Raman, 2 observasi kualitatif, dan 1 coverage record.</p></div><div class="nf-fp-actions"><button id="nfFlaxPostApprove" class="btn primary compact" disabled>Approve Raman supplement</button><button id="nfFlaxPostPublish" class="btn danger compact" disabled>Publish Raman supplement</button><button id="nfFlaxPostRefresh" class="btn secondary compact">Refresh</button></div></div><div id="nfFlaxPostSummary" class="summary-grid release-summary"></div><div id="nfFlaxPostStatus" class="release-status-note"></div><div id="nfFlaxPostBody"><div class="muted">Loading ${GROUP}…</div></div>`;host.prepend(p);$('#nfFlaxPostApprove')?.addEventListener('click',approve);$('#nfFlaxPostPublish')?.addEventListener('click',publish);$('#nfFlaxPostRefresh')?.addEventListener('click',refresh);return p}
function sync(){const isFlax=activeFiber()===FIBER_ID,p=$('#nfFlaxPostAuditPanel');if(p){p.hidden=!isFlax;if(isFlax)p.classList.remove('nf-hidden-by-fiber')}}
const card=(v,l)=>`<div class="summary-card"><b>${esc(v)}</b><span>${esc(l)}</span></div>`;
async function refresh(){const p=ensurePanel();if(!p)return;sync();if(activeFiber()!==FIBER_ID||busy)return;busy=true;try{if(!role)await resolveRole();const d=await rpc('get_natfiber_supplement_preview',{target_fiber_id:FIBER_ID,target_release_group:GROUP});if(!d)throw new Error('Editor session required.');const s=d.summary||{},items=d.items||[],sel=Number(s.selected_items||0),app=Number(s.approved_items||0),holds=Number(s.hold_items||0),all=sel>0&&sel===app&&holds===0,published=items.length>0&&items.every(i=>i.record?.is_public===true&&i.record?.record_status==='PUBLISHED');$('#nfFlaxPostSummary').innerHTML=[card(sel,'Selected'),card(app,'Approved'),card(holds,'Selected HOLD'),card(items.length,'Supplement items')].join('');$('#nfFlaxPostApprove').disabled=!(role==='ADMIN'&&sel>0&&app<sel&&holds===0);$('#nfFlaxPostPublish').disabled=!(role==='ADMIN'&&all&&!published);$('#nfFlaxPostStatus').innerHTML=published?'<strong>PUBLISHED.</strong> Raman supplement sudah public.':all?'<strong>APPROVED · PRIVATE.</strong> Siap dipublikasikan.':`<strong>PRIVATE.</strong> ${sel-app} item menunggu approval.`;$('#nfFlaxPostBody').innerHTML=`<div class="nf-fp-note"><strong>Publication guard:</strong> ¹H-NMR dan XRF tetap NOT_FOUND/HOLD; supplement ini tidak mengubah keduanya. Tidak ada figure Raman yang direhost karena figure-level rights belum terselesaikan.</div><div class="nf-fp-table"><table><thead><tr><th>ID</th><th>Label</th><th>Table</th><th>Status</th></tr></thead><tbody>${items.map(i=>`<tr><td><b>${esc(i.record_id)}</b></td><td>${esc(i.public_label||'')}</td><td>${esc(i.data_table||'')}</td><td class="${i.editor_status==='APPROVED'?'nf-fp-ok':''}">${esc(i.editor_status||'')}</td></tr>`).join('')}</tbody></table></div>`}catch(e){$('#nfFlaxPostBody').innerHTML=`<div class="message error">${esc(e.message||e)}</div>`}finally{busy=false}}
async function approve(){if(role!=='ADMIN')return;if(!confirm('Approve 4 item Raman supplement NF-0004?\n\nApproval belum mempublikasikan data.'))return;try{await rpc('approve_natfiber_supplement',{target_fiber_id:FIBER_ID,target_release_group:GROUP});await refresh()}catch(e){alert(e.message||e)}}
async function publish(){if(role!=='ADMIN')return;if(!confirm('Publish FLAX_POST_AUDIT_V1?\n\nHanya 4 item Raman yang SELECTED + APPROVED akan dipublikasikan.'))return;try{await rpc('publish_natfiber_supplement',{target_fiber_id:FIBER_ID,target_release_group:GROUP});await refresh();alert('NF-0004 Raman supplement published.')}catch(e){alert(e.message||e)}}
function boot(){addStyle();setInterval(()=>{if(!$('#editorApp'))return;ensurePanel();sync();const now=activeFiber();if(now!==lastFiber){lastFiber=now;if(now===FIBER_ID)refresh()}},500);document.addEventListener('click',e=>{if(e.target.closest('[data-view="preview"]'))setTimeout(()=>{sync();if(activeFiber()===FIBER_ID)refresh()},120)});setTimeout(async()=>{await resolveRole();ensurePanel();sync();if(activeFiber()===FIBER_ID)refresh()},450)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
