/* NatFiber Encyclopedia — NF-0004 Flax Public QA v1.0 */
(function(){
'use strict';
const CFG=window.NATFIBER_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>{try{return window.NF_I18N?.getLang?.()||localStorage.getItem('natfiber_lang')||'id'}catch{return'id'}};
const L=(a,b)=>lang()==='id'?a:b;
const fmt=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const currentFiber=()=>($('#fiberId')?.textContent||'').trim();
let cache=null,busy=false;
async function profile(){
  if(cache?.fiber?.fiber_id==='NF-0004')return cache;
  if(!CFG.supabaseUrl||!CFG.publishableKey||busy)return cache;
  busy=true;
  try{const r=await fetch(`${CFG.supabaseUrl}/rest/v1/rpc/get_natfiber_profile`,{method:'POST',headers:{apikey:CFG.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({target_fiber_id:'NF-0004'})});if(!r.ok)return null;cache=await r.json();return cache;}finally{busy=false;}
}
function panelTitle(sel,text){const h=$(sel)?.closest('.global-panel')?.querySelector('h4');if(h)h.textContent=text;}
function showGlobal(hasGlobal,hasMedia){const gh=$('#globalHero'),gt=$('.tab[data-tab="global"]'),gg=$('.tab[data-tab="gallery"]');if(gh){gh.hidden=!(hasGlobal||hasMedia);gh.style.display=(hasGlobal||hasMedia)?'':'none';}if(gt){gt.hidden=!hasGlobal;gt.style.display=hasGlobal?'':'none';}if(gg){gg.hidden=!hasMedia;gg.style.display=hasMedia?'':'none';}}
function heroMedia(media){const hero=media.find(x=>x.is_hero)||media[0];if(!hero)return;const im=$('#heroFiberImage');if(im){im.src=hero.asset_path||hero.original_file_url||'';im.alt=lang()==='id'?(hero.alt_text_id||hero.title):(hero.alt_text_en||hero.title);im.style.visibility='visible';im.onerror=()=>im.style.visibility='hidden';im.onload=()=>im.style.visibility='visible';}const cr=$('#heroMediaCredit');if(cr)cr.innerHTML=`${esc(hero.attribution_text||hero.creator||'')}${hero.license_url?` · <a href="${esc(hero.license_url)}" target="_blank" rel="noopener">${esc(hero.license_name||'License')}</a>`:''}`;}
function renderFlaxGlobal(p){
  const prod=p.production_stats||[],trade=p.trade_stats||[],dist=p.distribution||[],media=p.media||[];
  const area=prod.find(x=>x.statistic_name==='Textile-flax cultivation area')||prod[0];
  const native=dist.filter(x=>x.distribution_type==='NATIVE_RANGE'),commercial=dist.filter(x=>x.distribution_type==='COMMERCIAL_PRODUCTION');
  const hasGlobal=Boolean(prod.length||trade.length||dist.length),hasMedia=Boolean(media.length);showGlobal(hasGlobal,hasMedia);heroMedia(media);if(!hasGlobal)return;
  const title=L('Produksi, perdagangan, dan sebaran Flax','Flax production, trade, and distribution');
  const desc=L('Luas budidaya textile flax Uni Eropa ditampilkan terpisah dari produksi dunia. NatFiber tidak mengubah 182.000 ha menjadi tonase dan tidak mengisi angka World FAOSTAT sebelum baris resmi terverifikasi.','EU textile-flax cultivation area is shown separately from world production. NatFiber does not convert 182,000 ha into tonnage and does not fill a World FAOSTAT value until the exact official row is verified.');
  if($('#globalHero h3'))$('#globalHero h3').textContent=title;if($('#tab-global .section-title h3'))$('#tab-global .section-title h3').textContent=title;if($('#globalHero .global-hero-content > p'))$('#globalHero .global-hero-content > p').textContent=desc;if($('#tab-global .section-title p'))$('#tab-global .section-title p').textContent=desc;
  const metrics=[[L('Luas textile flax Uni Eropa','EU textile-flax area'),area?`${fmt(area.value)} ${esc(area.unit||'ha')}`:'—',area?`${area.year} · ${L('luas budidaya, bukan tonase','cultivated area, not tonnage')}`:'—'],[L('Produksi dunia FAOSTAT terbaru','Latest World FAOSTAT production'),L('HOLD — belum terverifikasi','HOLD — not yet verified'),L('Tidak diestimasi dari sumber sekunder','Not estimated from secondary sources')],[L('Observasi perdagangan terverifikasi','Verified trade observations'),String(trade.length),'HS 530121'],[L('Wilayah produksi utama UE','Main EU production regions'),String(commercial.length),commercial.map(x=>x.place_name).join(' · ')]];
  const mh=metrics.map(([k,v,n])=>`<div class="global-metric"><span>${esc(k)}</span><strong>${esc(v)}</strong><small>${esc(n)}</small></div>`).join('');if($('#globalHeroMetrics'))$('#globalHeroMetrics').innerHTML=mh;if($('#globalMetrics'))$('#globalMetrics').innerHTML=mh;
  panelTitle('#productionTrend',L('Observasi resmi budidaya textile flax','Official textile-flax cultivation observation'));const tn=$('#productionTrend')?.closest('.global-panel')?.querySelector('p.muted');if(tn)tn.textContent=L('Satuan hektare. Baris ini tidak mewakili produksi tonase dunia.','Unit: hectares. This row is not world production tonnage.');if($('#productionTrend'))$('#productionTrend').innerHTML=area?`<div class="distribution-card"><strong>${esc(area.country_or_region)} · ${area.year}</strong><p>${fmt(area.value)} ${esc(area.unit||'')} · ${esc(area.commodity_definition||'Textile flax')}</p><span>${esc(area.definition_warning||'')}</span></div>`:'<div class="muted">—</div>';
  panelTitle('#producerBars',L('Wilayah produksi textile flax utama','Main textile-flax production regions'));if($('#producerBars'))$('#producerBars').innerHTML=commercial.map(x=>`<div class="distribution-card" style="margin-bottom:10px"><strong>${esc(x.place_name)}</strong><p>${esc(x.description||'')}</p><span>${esc(x.source_organization||'')}</span></div>`).join('')||'<div class="muted">—</div>';
  panelTitle('#nativeRangeBox',L('Sebaran alami botani','Botanical native range'));if($('#nativeRangeBox'))$('#nativeRangeBox').innerHTML=native.map(x=>`<div class="distribution-card"><strong>${esc(x.place_name)}</strong><p>${esc(x.description||'')}</p><span>${esc(x.source_organization||'')}</span></div>`).join('')||'<div class="muted">—</div>';
  panelTitle('#commercialDistribution',L('Perdagangan HS 530121 — flax broken/scutched, not spun','HS 530121 trade — flax broken/scutched, not spun'));if($('#commercialDistribution'))$('#commercialDistribution').innerHTML=trade.map(x=>`<div class="distribution-card" style="margin-bottom:10px"><strong>${esc(x.country_or_region)} · ${esc(x.trade_flow)} · ${x.year}</strong><p>${fmt(x.value)} ${esc(x.unit||'')} · ${esc(x.product_form||x.commodity_definition||'')}</p><span>${esc(x.definition_warning||x.source_organization||'')}</span></div>`).join('')||'<div class="muted">—</div>';
  panelTitle('#historicalProduction',L('Batas data wajib','Mandatory data boundaries'));const hn=$('#historicalProduction')?.closest('.global-panel')?.querySelector('p.muted');if(hn)hn.textContent=L('NatFiber mempertahankan perbedaan antara luas budidaya, tonase produksi, dan arus perdagangan.','NatFiber preserves the distinction between cultivated area, production tonnage, and trade flows.');const bounds=[L('182.000 ha UE 2024 adalah luas textile flax, bukan produksi serat dalam ton.','EU 182,000 ha in 2024 is textile-flax area, not fibre tonnage.'),L('Exact World / Flax fibre and tow / latest FAOSTAT tetap HOLD sampai baris resmi diperoleh.','Exact World / Flax fibre and tow / latest FAOSTAT remains HOLD until the official row is retrieved.'),L('HS 530121 adalah flax broken or scutched, but not spun; arus perdagangan tidak sama dengan produksi biologis.','HS 530121 is flax broken or scutched, but not spun; trade flow is not biological production.'),L('Data seed/linseed/oil tidak digunakan sebagai data intrinsic bast fibre.','Seed/linseed/oil data are not used as intrinsic bast-fibre data.')];if($('#historicalProduction'))$('#historicalProduction').innerHTML=bounds.map((x,i)=>`<span class="history-chip"><b>${i+1}</b> ${esc(x)}</span>`).join('');
}
if(typeof renderGlobalFootprint==='function'){const prev=renderGlobalFootprint;renderGlobalFootprint=function(p){if(p?.fiber?.fiber_id==='NF-0004')return renderFlaxGlobal(p);return prev(p)};try{if(typeof currentProfile!=='undefined'&&currentProfile?.fiber?.fiber_id==='NF-0004')renderFlaxGlobal(currentProfile)}catch{}}
function obsValue(o){if(o.value_numeric!=null)return `${fmt(o.value_numeric)}${o.unit?` ${esc(o.unit)}`:''}${o.value_text?` · ${esc(o.value_text)}`:''}`;if(o.value_min!=null||o.value_max!=null)return `${fmt(o.value_min)}–${fmt(o.value_max)}${o.unit?` ${esc(o.unit)}`:''}`;return esc(o.value_text||'—')}
async function renderTechnique(tech){
  const p=await profile();if(!p||currentFiber()!=='NF-0004')return;const body=$('#charTechniqueBody');if(!body)return;
  if(['H_NMR','XRF'].includes(tech)){$$('#charTechniqueNav .char-tech-btn').forEach(x=>x.classList.toggle('active',x.dataset.tech===tech));const msg=tech==='H_NMR'?L('Tidak ada dataset ¹H-NMR intrinsic raw-flax-fibre yang defensible ditemukan pada research pass. Extract/derived-fraction NMR tidak dipromosikan menjadi intrinsic fibre.','No defensible intrinsic raw-flax-fibre ¹H-NMR dataset was found in the research pass. Extract/derived-fraction NMR is not promoted to intrinsic fibre.'):L('Tidak ada fingerprint XRF intrinsic organic flax fibre yang defensible ditemukan. XRF pada material termodifikasi/ash tidak dipromosikan menjadi komposisi intrinsic fibre.','No defensible intrinsic organic flax-fibre XRF fingerprint was found. XRF on modified material/ash is not promoted to intrinsic-fibre composition.');body.innerHTML=`<div class="char-tech-summary"><div><span>${L('Bukti','Evidence')}</span><strong>${L('BELUM DITEMUKAN','NOT FOUND')}</strong></div><p>${esc(msg)}</p></div>`;return;}
  const cov=(p.characterization_coverage||[]).find(x=>x.technique===tech),recs=(p.characterization_records||[]).filter(x=>x.technique===tech);if(!cov)return;$$('#charTechniqueNav .char-tech-btn').forEach(x=>x.classList.toggle('active',x.dataset.tech===tech));body.innerHTML=`<div class="char-tech-summary"><div><span>${L('Bukti','Evidence')}</span><strong>${esc(String(cov.evidence_level||'').replaceAll('_',' '))}</strong></div><p>${esc(cov.main_limitation||'')}</p></div><div class="char-record-grid">${recs.map(r=>{const obs=(p.characterization_observations||[]).filter(o=>o.characterization_id===r.characterization_id),src=r.doi?`https://doi.org/${encodeURIComponent(r.doi)}`:'';return `<article class="char-record"><div class="char-record-head"><div><div class="char-record-id">${esc(r.characterization_id)} · ${esc(tech)}</div><h4>${esc(r.sample_condition||'—')}</h4></div><span class="char-context">${esc(r.context_type||'')}</span></div><div class="char-kv"><b>${L('Perlakuan','Treatment')}</b><span>${esc(r.treatment||'—')}</span><b>${L('Instrumen','Instrument')}</b><span>${esc(r.instrument||'—')}</span><b>${L('Kondisi pengukuran','Measurement conditions')}</b><span>${esc(r.measurement_conditions||'—')}</span><b>${L('Verifikasi','Verification')}</b><span>${esc(r.verification_level||'—')}</span></div>${r.interpretation?`<p class="char-interpretation">${esc(r.interpretation)}</p>`:''}${obs.length?`<div class="char-observations"><strong>${L('Observasi sumber','Source observations')}</strong><div class="char-observation-grid">${obs.map(o=>`<div class="char-observation"><span>${esc(o.parameter)}</span><b>${obsValue(o)}</b></div>`).join('')}</div></div>`:''}<div class="char-record-links">${src?`<a href="${esc(src)}" target="_blank" rel="noopener">${L('Buka sumber','Open source')} ↗</a>`:''}</div></article>`}).join('')}</div>`;
}
function ensureCharNav(){
  const nav=$('#charTechniqueNav');if(currentFiber()!=='NF-0004'){nav?.querySelectorAll('[data-flax-extra="1"]').forEach(x=>x.remove());return}if(!nav)return;const p=cache,available=new Set((p?.characterization_coverage||[]).map(x=>x.technique));
  for(const tech of ['TGA','DTG','RAMAN','H_NMR','XRF']){const shouldShow=['H_NMR','XRF'].includes(tech)||available.has(tech);if(!shouldShow||nav.querySelector(`[data-tech="${tech}"]`))continue;const b=document.createElement('button');b.type='button';b.className='char-tech-btn';b.dataset.tech=tech;b.dataset.flaxExtra='1';const label=tech==='H_NMR'?'¹H-NMR':tech==='RAMAN'?'Raman / NIR-FT-Raman':tech;const small=['H_NMR','XRF'].includes(tech)?L('Belum ditemukan','Not found'):(p?.characterization_coverage||[]).find(x=>x.technique===tech)?.evidence_level?.replaceAll('_',' ')||L('Bukti','Evidence');b.innerHTML=`<span>${esc(label)}</span><small>${esc(small)}</small>`;b.addEventListener('click',()=>renderTechnique(tech));const anchor=nav.querySelector('[data-tech="C13_NMR"]');anchor?nav.insertBefore(b,anchor):nav.appendChild(b)}
  const notice=$('.char-notice');if(notice)notice.innerHTML=`<strong>${L('Kontrol NF-0004:','NF-0004 controls:')}</strong> ${L('TGA dan DTG dipisahkan. Raman diperlakukan sebagai teknik intrinsic yang berdiri sendiri. ¹H-NMR dan XRF intrinsic tetap NOT_FOUND dan tidak diisi dengan data extract, ash, atau material termodifikasi.','TGA and DTG are separate. Raman is treated as a standalone intrinsic technique. Intrinsic ¹H-NMR and XRF remain NOT_FOUND and are not filled using extract, ash, or modified-material data.')}`;
  const desc=$('.char-desc');if(desc)desc.textContent=L('SEM, FTIR, XRD, DSC, TGA, DTG, Raman dan ¹³C-NMR ditampilkan secara source-resolved; gap intrinsic ¹H-NMR/XRF dipertahankan eksplisit.','SEM, FTIR, XRD, DSC, TGA, DTG, Raman and ¹³C-NMR are shown source-resolved; intrinsic ¹H-NMR/XRF gaps remain explicit.');
}
async function refreshFlax(){if(currentFiber()!=='NF-0004')return;cache=null;await profile();ensureCharNav()}
setInterval(()=>{if(currentFiber()==='NF-0004'&&!cache)profile().then(ensureCharNav);else ensureCharNav()},600);document.addEventListener('click',e=>{if(e.target.closest('.language-switch [data-lang]'))setTimeout(refreshFlax,180)});console.info('[NatFiber] NF-0004 Flax Public QA v1.0 loaded.');
})();
