/* NatFiber NF-0003 Jute Public QA v1.0 */
(function(){
'use strict';
const CFG=window.NATFIBER_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>{try{return window.NF_I18N?.getLang?.()||localStorage.getItem('natfiber_lang')||'id'}catch{return'id'}};
const L=(a,b)=>lang()==='id'?a:b, fmt=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const currentFiber=()=>($('#fiberId')?.textContent||'').trim(); let cache=null,busy=false;
async function profile(){if(cache?.fiber?.fiber_id==='NF-0003')return cache;if(!CFG.supabaseUrl||!CFG.publishableKey||busy)return cache;busy=true;try{const r=await fetch(`${CFG.supabaseUrl}/rest/v1/rpc/get_natfiber_profile`,{method:'POST',headers:{apikey:CFG.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({target_fiber_id:'NF-0003'})});if(!r.ok)return null;cache=await r.json();return cache}finally{busy=false}}
function title(sel,text){const h=$(sel)?.closest('.global-panel')?.querySelector('h4');if(h)h.textContent=text}
function renderJuteGlobal(p){
 const prod=p.production_stats||[],trade=p.trade_stats||[],dist=p.distribution||[],media=p.media||[],hero=media.find(x=>x.is_hero)||media[0],india=prod.find(x=>x.country_or_region==='India'&&x.year===2023),native=dist.filter(x=>x.distribution_type==='NATIVE_RANGE');
 const gt=$('.tab[data-tab="global"]'),gg=$('.tab[data-tab="gallery"]'),gh=$('#globalHero');if(gt){gt.hidden=false;gt.style.display=''}if(gg){gg.hidden=!media.length;gg.style.display=media.length?'':'none'}if(gh){gh.hidden=false;gh.style.display=''}
 const t=L('Produksi, perdagangan, dan sebaran Jute','Jute production, trade, and distribution'),d=L('Statistik Jute mengikuti definisi komoditas sumber. “Jute & Mesta”, “Jute and jute-like fibres”, dan heading HS campuran bukan data spesies murni.','Jute statistics follow source commodity definitions. “Jute & Mesta”, “Jute and jute-like fibres”, and mixed HS headings are not species-pure data.');
 if($('#globalHero h3'))$('#globalHero h3').textContent=t;if($('#tab-global .section-title h3'))$('#tab-global .section-title h3').textContent=t;if($('#globalHero .global-hero-content > p'))$('#globalHero .global-hero-content > p').textContent=d;if($('#tab-global .section-title p'))$('#tab-global .section-title p').textContent=d;
 if(hero){const im=$('#heroFiberImage');if(im){im.src=hero.asset_path||hero.original_file_url||'';im.alt=lang()==='id'?(hero.alt_text_id||hero.title):(hero.alt_text_en||hero.title);im.style.visibility='visible';im.onerror=()=>im.style.visibility='hidden'}const cr=$('#heroMediaCredit');if(cr)cr.innerHTML=`${esc(hero.attribution_text||hero.creator||'')}${hero.license_url?` · <a href="${esc(hero.license_url)}" target="_blank" rel="noopener">${esc(hero.license_name||'License')}</a>`:''}`}
 const m=[[L('India — Jute & Mesta 2023–24','India — Jute & Mesta 2023–24'),india?`${fmt(india.value)} ${esc(india.unit||'t')}`:'—',L('Kategori resmi campuran; bukan pure jute','Official mixed crop category; not pure jute')],[L('Seri dunia FAOSTAT terbaru','Latest world FAOSTAT series'),L('Belum terselesaikan','Not yet resolved'),L('Gold-standard gate; jangan diestimasi','Gold-standard gate; do not estimate')],[L('Observasi perdagangan 2023','2023 trade observations'),String(trade.length),L('Semua MIXED_COMMODITY','All MIXED_COMMODITY')],[L('Spesies budidaya utama','Primary cultivated species'),'2','C. capsularis + C. olitorius']];const mh=m.map(([k,v,n])=>`<div class="global-metric"><span>${esc(k)}</span><strong>${esc(v)}</strong><small>${esc(n)}</small></div>`).join('');if($('#globalHeroMetrics'))$('#globalHeroMetrics').innerHTML=mh;if($('#globalMetrics'))$('#globalMetrics').innerHTML=mh;
 title('#productionTrend',L('Observasi produksi resmi yang telah diverifikasi','Verified official production observations'));const tn=$('#productionTrend')?.closest('.global-panel')?.querySelector('p.muted');if(tn)tn.textContent=L('Baris ini bukan satu seri homogen; definisi komoditas dan tahun berbeda.','These rows are not one homogeneous series; commodity definitions and years differ.');const mx=Math.max(...prod.map(x=>Number(x.value||0)),1);if($('#productionTrend'))$('#productionTrend').innerHTML=prod.map(x=>`<div class="trend-col"><div class="trend-value">${fmt(x.value)}</div><div class="trend-bar-wrap"><div class="trend-bar" style="height:${Math.max(8,100*Number(x.value||0)/mx)}%"></div></div><div class="trend-year">${esc(x.country_or_region)}<small style="display:block">${x.year}</small></div></div>`).join('');
 title('#producerBars',L('Definisi komoditas produksi','Production commodity definitions'));if($('#producerBars'))$('#producerBars').innerHTML=prod.map(x=>`<div class="distribution-card" style="margin-bottom:10px"><strong>${esc(x.country_or_region)} · ${x.year}</strong><p>${fmt(x.value)} ${esc(x.unit||'')} · ${esc(x.commodity_definition||'')}</p><span>${esc(x.definition_warning||'')}</span></div>`).join('');
 title('#nativeRangeBox',L('Sebaran alami botani','Botanical native ranges'));if($('#nativeRangeBox'))$('#nativeRangeBox').innerHTML=native.map(x=>`<div class="distribution-card"><strong>${esc(x.taxon_name||x.place_name)}</strong><p>${esc(x.place_name)}. ${esc(x.description||'')}</p><span>${esc(x.source_organization||'')}</span></div>`).join('')||'<div class="muted">—</div>';
 title('#commercialDistribution',L('Bukti negara produksi yang tersimpan','Stored production-country evidence'));if($('#commercialDistribution'))$('#commercialDistribution').innerHTML=[...new Set(prod.map(x=>x.country_or_region))].map(x=>`<span class="distribution-chip">${esc(x)}</span>`).join('')||'<div class="muted">—</div>';
 title('#historicalProduction',L('Batas data wajib','Mandatory data boundaries'));const hn=$('#historicalProduction')?.closest('.global-panel')?.querySelector('p.muted');if(hn)hn.textContent=L('Angka dunia terbaru ditahan sampai baris FAOSTAT langsung terverifikasi.','The latest world value remains withheld until the exact FAOSTAT row is directly verified.');const b=[L('FAO 2006 memakai “Jute and jute-like fibres”.','FAO 2006 uses “Jute and jute-like fibres”.'),L('India 2023–24 adalah “Jute & Mesta”.','India 2023–24 is “Jute & Mesta”.'),L('HS 530310/530390/530710 mencakup serat bast lain.','HS 530310/530390/530710 include other bast fibres.'),L('Tidak ada angka world-latest yang diestimasi.','No latest-world figure is estimated.')];if($('#historicalProduction'))$('#historicalProduction').innerHTML=b.map((x,i)=>`<span class="history-chip"><b>${i+1}</b> ${esc(x)}</span>`).join('');
}
if(typeof renderGlobalFootprint==='function'){const prev=renderGlobalFootprint;renderGlobalFootprint=function(p){if(p?.fiber?.fiber_id==='NF-0003')return renderJuteGlobal(p);return prev(p)};try{if(typeof currentProfile!=='undefined'&&currentProfile?.fiber?.fiber_id==='NF-0003')renderJuteGlobal(currentProfile)}catch{}}
function ov(o){if(o.value_numeric!=null)return `${fmt(o.value_numeric)}${o.unit?` ${esc(o.unit)}`:''}${o.value_text?` · ${esc(o.value_text)}`:''}`;if(o.value_min!=null||o.value_max!=null)return `${fmt(o.value_min)}–${fmt(o.value_max)}${o.unit?` ${esc(o.unit)}`:''}`;return esc(o.value_text||'—')}
async function thermal(tech){const p=await profile();if(!p||currentFiber()!=='NF-0003')return;const cov=(p.characterization_coverage||[]).find(x=>x.technique===tech),recs=(p.characterization_records||[]).filter(x=>x.technique===tech),body=$('#charTechniqueBody');if(!body||!cov)return;$$('#charTechniqueNav .char-tech-btn').forEach(x=>x.classList.toggle('active',x.dataset.tech===tech));body.innerHTML=`<div class="char-tech-summary"><div><span>${L('Bukti','Evidence')}</span><strong>${esc(String(cov.evidence_level||'').replaceAll('_',' '))}</strong></div><p>${esc(cov.main_limitation||'')}</p></div><div class="char-record-grid">${recs.map(r=>{const obs=(p.characterization_observations||[]).filter(o=>o.characterization_id===r.characterization_id),src=r.doi?`https://doi.org/${encodeURIComponent(r.doi)}`:'';return `<article class="char-record"><div class="char-record-head"><div><div class="char-record-id">${esc(r.characterization_id)} · ${tech}</div><h4>${esc(r.sample_condition||'—')}</h4></div></div><div class="char-kv"><b>${L('Instrumen','Instrument')}</b><span>${esc(r.instrument||'—')}</span><b>${L('Kondisi pengukuran','Measurement conditions')}</b><span>${esc(r.measurement_conditions||'—')}</span><b>${L('Verifikasi','Verification')}</b><span>${esc(r.verification_level||'—')}</span></div>${r.interpretation?`<p class="char-interpretation">${esc(r.interpretation)}</p>`:''}${obs.length?`<div class="char-observations"><strong>${L('Observasi sumber','Source observations')}</strong><div class="char-observation-grid">${obs.map(o=>`<div class="char-observation"><span>${esc(o.parameter)}</span><b>${ov(o)}</b></div>`).join('')}</div></div>`:''}<div class="char-record-links">${src?`<a href="${esc(src)}" target="_blank" rel="noopener">${L('Buka sumber','Open source')} ↗</a>`:''}</div></article>`}).join('')}</div>`}
function nav(){const n=$('#charTechniqueNav');if(currentFiber()!=='NF-0003'){n?.querySelectorAll('[data-jute-extra="1"]').forEach(x=>x.remove());return}if(!n)return;for(const tech of ['TGA','DTG']){if(n.querySelector(`[data-tech="${tech}"]`))continue;const b=document.createElement('button');b.type='button';b.className='char-tech-btn';b.dataset.tech=tech;b.dataset.juteExtra='1';b.innerHTML=`<span>${tech}</span><small>STRONG EVIDENCE</small>`;b.addEventListener('click',()=>thermal(tech));const a=n.querySelector('[data-tech="H_NMR"]');a?n.insertBefore(b,a):n.appendChild(b)}}
setInterval(nav,500);document.addEventListener('click',e=>{if(e.target.closest('.language-switch [data-lang]'))setTimeout(()=>{cache=null;nav()},150)});console.info('[NatFiber] NF-0003 Jute Public QA v1.0 loaded.');
})();
